projectsettings:
  servicehook:
    - name: "new webhook 1"
      event: "Pull request commented on"
      url: "http://127.0.0.1:8080/webhook"
    - name: "new webhook 2"
      event: "Pull request created"
      url: "http://127.0.0.1:8080/webhook"
    - name: "new webhook 3"
      event: "Pull request updated"
      url: "http://127.0.0.1:8080/webhook"
  serviceconnections:
    - name: "Docker Repository"
      type: "Docker Registry"
      url: "https://repo.local"
      user: "user"
      password: "pass"
      grant_access: true
    - name: "Nuget Repository"
      type: "NuGet"
      auth: "ApiKey"
      url: "https://nuget.local"
      apiKey: "key"
      grant_access: true
    - name: "NPM Repository"
      type: "npm"
      auth: "user and pass"
      url: "https://npm.local"
      user: "user"
      password: "pass"
      grant_access: true
    - name: "DefectDojo"
      type: "Generic"
      auth: "user and pass"
      url: "https://dd.local"
      user: ""
      password: "key"
      grant_access: false
pipelines:
  library:
    - name: "nexusRepository"
      overwrite: "true"
      pipeline_permissions: "open"
      variables:
        - name: "nexus_url"
          value: "https://nexus.local"
          is_secret: "false" # default is false
        - name: "nexus_user"
          value: "user"
        - name: "nexus_pass"
          value: "pass"
          is_secret: "true"
    - name: "Database Build Server"
      overwrite: "false"  # default is false
      pipeline_permissions: "restrict" # default is restrict
      variables:
        - name: "db"
          value: "172.20.20.20"
        - name: "db_user"
          value: "user"
        - name: "db_pass"
          value: "pass"
          is_secret: "true"
    - name: "WebServer"
      variables:
        - name: "WebServerurl"
          value: "localhost"
        - name: "user"
          value: "user"
        - name: "pass"
          value: "pass"
          is_secret: "true"
